/*
    Generated by AI
*/

#include <stdio.h>

int main() {
    FILE *fp = fopen("binary_file.bin", "wb");
    if (fp == NULL) {
        perror("Error creating file");
        return 1;
    }

    // Write some binary data
    unsigned char data[] = {0x12, 0x34, 0x56, 0x78, 0x9A};
    fwrite(data, sizeof(unsigned char), sizeof(data), fp);

    fclose(fp);
    printf("Binary file created successfully.\n");
    return 0;
}
