/*
    Generated by AI
*/

#include <stdio.h>
int main() {
    FILE *fp = fopen("binary_file.bin", "rb");
    if (fp == NULL) {
        perror("Error opening file");
        return 1;
    }

    // Read binary data
    unsigned char data[5];  // Adjust the size as needed
    size_t n = fread(data, sizeof(unsigned char), sizeof(data), fp);
    if (n != sizeof(data)) {
        perror("Error reading file");
        return 1;
    }

    // Print the data
    for (size_t i = 0; i < n; i++) {
        printf("%02X ", data[i]);
    }
    printf("\n");

    fclose(fp);
    return 0;
}
